### ISSUE TITLE
undefined method "&" for "K":String

### ISSUE THREAD

**Issue by nutheory** [nathancolgate/s3-swf-upload-plugin#9] opened 2010-09-08 10:39 UTC
using ruby 1.9.2 and rails 3, line 36 of the s3_upload controller would output the error message...

undefined method "&" for "K":String

that made no sense to me, but it must have something to do with the signature file and the method "b64_hmac_sha1"... however i found this snippet in amazon s3 docs that got it working for me...

signature = Base64.encode64(OpenSSL::HMAC.digest(OpenSSL::Digest::Digest.new('sha1'), secret_key, policy)).gsub("\n","")

i've seen similar errors in ruby 1.9 due to a change in the way strings are encoded. just a FYI

**Comment by nathancolgate** [comment] 2010-09-08 14:55
Thanks for the heads up AND a proposed fix!

If anyone else runs into this problem: don't panic.  Use nutheory's fix above in the controller that is generated and you'll be good to go!

It may be a while before I have a chance to test/ implement his fix, so don't wait on me :).

**Comment by mattheworiordan** [comment] 2010-10-29 00:13
Thanks, had the same issue, but I can confirm that this solution works in 1.9.2.  Thanks Nutheory.

**Comment by mrrooijen** [comment] 2010-11-30 01:17
Thanks for posting that solution. I actually came across the same error except that the `K` was an `N`. Regardless, the solution above worked great for me. Ruby 1.9.2 Rails 3.0.3. Thanks!

**Comment by kevinansfield** [comment] 2010-12-03 01:34
Thanks. This fixed the same issue for me too.

**Comment by dvdplm** [comment] 2010-12-21 15:20
I dug into this before checking the "Issues" and gained some clarity on the root cause. As mentioned above this is caused by changes in Ruby 1.9 where String#[] doesn't return an ascii code anymore (for a good reason I might add; that was never a good idea anyway). The code in signature.rb relies on str[some_index] to return a Fixnum to be and'ed (&) with some mask. In Ruby 1.9 str[some_index] returns a one char String, hence the exception.

The fix is reasonably easy: tuck on a .ord before and'ing (see http://apidock.com/ruby/Integer/ord) and both rubies should return an int.

I'll fork and make the change and hopefully we can get this fixed at the core.

**Comment by technologythree** [comment] 2011-02-20 19:32
Thanks fixed the issue

**Comment by krzkrzkrz** [comment] 2011-02-25 04:32
Thanks for the solution. Worked for me as well

**Comment by ugifractal** [comment] 2011-05-19 08:38
Thanks working :)

**Comment by ghost** [comment] 2011-10-25 07:42
worked for me too

**Comment by nathancolgate** [comment] 2012-06-22 17:18
This seems to be working for everyone. Closing ticket. Thanks again @nutheory

**Closed as completed by nathancolgate** 2012-06-22 17:18 UTC
