### ISSUE TITLE
Graphic not showing up

### ISSUE THREAD

**Issue by maxgronlund** [nathancolgate/s3-swf-upload-plugin#11] opened 2010-09-09 18:33 UTC
I followed the great tutorial to the letter, and it looks right, but when I ad files they don't show up.

please have a look at: http://furious-ocean-71.heroku.com/ as you can se there is no graphics for the files? I got the same issue on local host.
I have uploaded a version of the demo project here http://sysx.dk/sites/default/files/swfuploader.zip

I'm running rails 3.0.0.
ruby 1.9.2 on localhost and 1.8.7 on heroku.

Files are uploading OK from Heroku but not from localhost?

**Comment by nathancolgate** [comment] 2010-09-09 18:37
Duplicate of issue 10.

**Closed as completed by nathancolgate** 2010-09-09 18:37 UTC
